[workspace]
resolver = "2"
members = [
    # "clients/rust", # excluded - mollusk-svm conflicts
    "interface",
    # "program", # excluded - mollusk-svm conflicts
]

[workspace.package]
authors = ["Anza Technology Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/config"
readme = "./README.md"
license-file = "./LICENSE"
edition = "2021"

[workspace.dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
borsh = "0.10"
kaigan = "0.2.6"
mollusk-svm = "0.7.0"
mollusk-svm-bencher = "0.7.0"
num-derive = "0.4"
num-traits = "0.2"
serde = "1.0.228"
serde_derive = "1.0.193"
solana-account = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-account-info = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-bincode = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-client = { git = "https://github.com/jupnet/jupnet-svm", branch = "fix/v3.1.2-script-build" }
solana-config-interface = { version = "2.0.0", path = "interface" }
solana-hash = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-instruction = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-msg = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-program = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-program-entrypoint = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-program-error = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-pubkey = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-sdk = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-sdk-ids = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-short-vec = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-system-interface = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
solana-rent = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
thiserror = "2.0.17"

[workspace.metadata.spellcheck]
config = "scripts/spellcheck.toml"

[patch.crates-io]
jupnet-signature = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
jupnet-signer = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps" }
spl-pod = { git = "https://github.com/jupnet/libraries", branch = "fix/sdk-deps" }
spl-type-length-value = { git = "https://github.com/jupnet/libraries", branch = "fix/sdk-deps" }
spl-discriminator = { git = "https://github.com/jupnet/libraries", branch = "fix/sdk-deps" }
